name : test-project
on : [push, workflow_dispatch]
jobs:
  tests:
    runs-on: windows-2022
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name : Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  deploy:
    runs-on: windows-2022
    steps:
      - name: testing jobs
        run : echo "tetsing jobs"
  testing:
    needs: deploy
    runs-on: windows-2022
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name : Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'