name : test-project
on : push
jobs:
  tests:
    runs-on: windows-2022
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name : Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run tests
        run : npm test